#!/usr/bin/perl
use strict;
use warnings;

my ($os) = @ARGV;


sub run_and_format {
    my $result = `@_ 2>&1`;
    if ($? != 0) {
        die "Command failed: @_\n$result";
    }
    chomp $result;
    print <<EOT;
## ```@_```

```
$result
```

EOT
}

print <<EOT;
# Runner Information (Linux)

EOT

my @commands = (
    'whoami',
    'pwd',
    'df -h .',
    'uname -a',
    'sysctl -a',
);

if ($os eq "Linux") {
    push @commands, (
        'cat /boot/config-$(uname -r)',
        'lsb_release -a',
    );
}

for my $command(@commands) {
    run_and_format($command);
}
