name: Build Script

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - run: |
          # スクリプトからコンテキストにはアクセスできないので引数として渡す
          ./tools/build-foo-bar --actor '${{ github.actor }}'
