name: GH

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - run: |
          gh auth status
          curl -sSf -H "authorization: token $GH_TOKEN" https://api.github.com/user
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


