name: GH

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - run: |
          DEBUG=api gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


