name: Runner Info

on:
  workflow_dispatch:
  schedule:
  - cron: '49 4 * * *'

jobs:
  build:
    strategy:
      matrix:
        include:
        - name: ubuntu
          runner: ubuntu-latest
        - name: macos
          runner: macos-latest

    name: '${{ matrix.name }}'
    runs-on: '${{ matrix.runner }}'
    timeout-minutes: 5
    concurrency:
      group: '${{ github.workflow }}-${{ matrix.runner }}'
      cancel-in-progress: true

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Checkout the wiki repository
      uses: actions/checkout@v3
      with:
        repository: "${{ github.repository }}.wiki"
        ref: master
        path: .wiki

    - name: Configure the GitHub wiki identity
      working-directory: .wiki
      run: |
        set -xeu -o pipefail
        git config user.name  "${GITHUB_ACTOR}[bot]"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: Generate the Wiki Page
      run: |
        set -xeu -o pipefail
        ./tools/runner-info "${{ runner.os }}" | tee .wiki/Runner-${{ runner.os }}.md
    - name: Update the wiki page
      working-directory: .wiki
      run: |
        set -xeu -o pipefail
        git add .
        if git commit -m "update the wiki page by bot (${GITHUB_WORKFLOW})" ; then
          git push origin master
        fi
